apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cruisecontrolbalances.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
  version: v1beta1
  scope: Namespaced
  names:
    kind: CruiseControlBalanceBalance
    listKind: CruiseControlBalanceBalanceList
    singular: cruisecontrolbalancebalance
    plural: cruisecontrolbalances
    shortNames:
    - cc
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties: {}
