apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cruisecontrols.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
  version: v1beta1
  scope: Namespaced
  names:
    kind: CruiseControl
    listKind: CruiseControlList
    singular: cruisecontrol
    plural: cruisecontrols
    shortNames:
    - cc
  additionalPrinterColumns:
  - name: Desired replicas
    description: The desired number of Cruise Control replicas
    JSONPath: .spec.replicas
    type: integer
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            replicas:
              type: integer
              minimum: 1
            image:
              type: string
            tlsSidecar:
              type: object
              properties:
                image:
                  type: string
                livenessProbe:
                  type: object
                  properties:
                    failureThreshold:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                      minimum: 0
                    periodSeconds:
                      type: integer
                    successThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                      minimum: 0
                logLevel:
                  type: string
                  enum:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
                readinessProbe:
                  type: object
                  properties:
                    failureThreshold:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                      minimum: 0
                    periodSeconds:
                      type: integer
                    successThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                      minimum: 0
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                    requests:
                      type: object
            resources:
              type: object
              properties:
                limits:
                  type: object
                requests:
                  type: object
            version:
              type: string
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  lastTransitionTime:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
            observedGeneration:
              type: integer
