apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaClusterRebalance
metadata:
  name: my-rebalance
  labels:
    strimzi.io/cluster: my-cluster
spec:
  goals:
    - DiskCapacityGoal
    - CpuCapacityGoal