// This concept is included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

:parent-context-cruise-control-overview: {context}

[id='con-cruise-control-overview-{context}']
= Cruise Control overview

Cruise Control is tool for simplifying the monitoring and rebalancing of Kafka partitions across a large-scale Kafka cluster.
You deploy Cruise Control alongside a Kafka cluster to:

* Monitor the cpu, disk, and network load of Kafka brokers.
* Propose balanced partition assignments, known as a partition rebalance proposal.
* Trigger partition reassignments based on those proposals.

The following sections explain how to xref:proc-deploying-cruise-control-{context}[deploy Cruise Control], xref:ref-cruise-control-configuration-{context}[set configuration options], xref:proc-interacting-with-cruise-control-api-{context}[use the Cruise Control API], and xref:proc-executing-cruise-control-rebalance-operation-{context}[execute a cluster rebalance operation].

:context: cruise-control-overview
