// This module is included in the following assemblies:
//
// assembly-cruise-control-concepts.adoc

[id='proc-deploying-cruise-control-{context}']
= Deploying Cruise Control

Deploy Cruise Control through the `Kafka` resource in the `cruiseControl` properties.

Refer to the xref:ref-sample-kafka-resource-config-deployment-configuration-kafka[sample Kafka YAML configuration] for an overview of the `Kafka` resource and its properties.

The properties relevant to the Cruise Control configuration are shown in this procedure.

You can configure these properties as part of a deployment or redeployment of the Kafka cluster.

.Prerequisites

* A Kubernetes cluster
* A running Cluster Operator

.Procedure

. Edit the `cruiseControl` properties for the `Kafka` resource.
+
The properties you can configure are shown in this example configuration:
+
[source,yaml,subs="attributes+"]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  cruiseControl:
    replicas: 1 <1>
    config: <2>
      default.goals: >
         com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,
         com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal
      cpu.balance.threshold: 1.1
      metadata.max.age.ms: 300000
      send.buffer.bytes: 131072
      ...
    resources: <3>
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    logging: debug <4>
    template: <5>
      pod:
        metadata:
          labels:
            label1: value1
        securityContext:
          runAsUser: 1000001
          fsGroup: 0
        terminationGracePeriodSeconds: 120
    readinessProbe: <6>
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe: <7>
      initialDelaySeconds: 15
      timeoutSeconds: 5
# ...
----
<1> Number of application instances, can be set to 1 to run or 0 to pause the application.
<2> Config specifies the Cruise Control configuration. xref:ref-cruise-control-configuration-{context}[Standard Cruise Control configuration may be provided, restricted to those properties not managed directly by {ProductName}].
<3> xref:assembly-resource-limits-and-requests-deployment-configuration-kafka[CPU and memory resources to reserve].
<4> Logging configuration, to log messages with a given severity (debug, info, warn, error, fatal) or above.
<5> xref:assembly-customizing-deployments-str[Customization of deployment templates and pods].
<6> xref:assembly-healthchecks-deployment-configuration-kafka[Healthcheck readiness probes].
<7> xref:assembly-healthchecks-deployment-configuration-kafka[Healthcheck liveness probes].

. Create or update the resource:
+
[source,shell,subs="+quotes"]
----
kubectl apply -f _kafka.yaml_
----

.What to do next

After configuring and deploying Cruise Control, you can create a xref:proc-cruise-control-create-rebalance-resource[create a KafkaRebalance resource]

.Additional resources

xref:type-CruiseControlTemplate-reference[].